import Head from 'next/head';
import Image from 'next/image';
// import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import type { GetServerSideProps, InferGetServerSidePropsType } from 'next';
import { useEffect } from 'react';
import { z } from 'zod';
import { github } from '../services/github';
import { githubPublicUserSchema } from '../services/github/schema';
import { useRequest } from '../hooks';

// const inter = Inter({ subsets: ['latin'] });

type Props = {
  username: string;
  color: string;
};

type Params = Pick<Props, 'username'>;

export const getServerSideProps: GetServerSideProps<
  Props,
  Params
> = async ctx => {
  return {
    props: {
      username: ctx.params?.username ?? '',
      color: (ctx.query.color as string | undefined) ?? '',
    },
  };
};

const validationSchema = githubPublicUserSchema.pick({
  avatarUrl: true,
  followers: true,
  name: true,
});

type GithubUser = z.infer<typeof validationSchema>;

type HomeProps = InferGetServerSidePropsType<typeof getServerSideProps>;

const Home = ({ color, username }: HomeProps) => {
  const { data, error, request } = useRequest<GithubUser>(
    () => github.getUser(username),
    {
      validationSchema,
    }
  );

  useEffect(() => {
    request();
  }, []);

  if (error) {
    return <div>Whoops 😅 Looks like something didn't go as planned 😵</div>;
  }

  if (!data) {
    return <div>loading...</div>;
  }

  return (
    <>
      <Head>
        <title>TS App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <>
          <Image
            src={data.avatarUrl}
            alt="profile photo"
            width={80}
            height={80}
          />

          <div className={styles.description}>
            <span style={{ color }}>{`${data.name} `}</span>
            {`has ${data.followers ?? '🙈'} followers`}
          </div>
        </>
      </main>
    </>
  );
};

export default Home;
